### ISSUE TITLE
edit --noedit with custom fields not working

### ISSUE THREAD

**Issue by thmatew** [Netflix-Skunkworks/go-jira#103]
Hi,
I want to use go-jira in a script to set a value to a custom field in an issue.
If I do 
`jira edit --noedit -o customfield_10042=3 PROJ-1`

it seems to work but nothing has change in my issue

if I don't use --noedit and edit it in vi for example
```
# issue: <no value>
update:
  comment:
    - add:
        body: |~

fields:
  summary: <no value>
  components: # Values:
  assignee:
    name:
  # watchers
  customfield_10110:
```
**customfield_10042: 3**
```
  priority: # Values:
    name: <no value>
  description: |~

# comments:
#

```

this will affect my issue, and update the custom field.

I try to use on a non custom field, and it works.
Do you have a way to do this ?
thx
