### ISSUE TITLE
escape or sanitize inputs

### ISSUE THREAD

**Issue by drrobotnik** [Netflix-Skunkworks/go-jira#115]
Fields to and from Jira can have any type of formatting. These fields should be escaped before being placed in the YAML templates.

For example:

```
fields:
  assignee:
    name: user
  description: As a visitor, I want clear information about XYZ^M
^M
Design updates located in assets^M
^M
*Notes:*^M
* XXXXXXXXXXX^M
* XXXXXXX ^M
* XXXXXXXXXX ^M
^M
_*Acceptance Criteria*_^M
1. XXXXXXXX^M

  customfield_13624: "."
transition:
  id: 21
  name: In Progress
```

Results in:

```
ERROR yaml: line 7: could not find expected ':'
? Invalid YAML syntax, edit again? (Y/n) 
```

In this case the description should be wrapped in parenthesis and if the story includes any special characters they should be escaped. Having to do this manually is cumbersome.

This is also true for custom commands and arguments.

For example:

```
  - name: release
    help: display stories related to a release
    script: |-
       {{jira}} list --template=list-stories --query "project = $JIRA_PROJECT AND status in (resolved, closed) and {{args.fixversion}}"
    args:
      - name: fixversion
        required: false
```

```
$ jira release fixversion="2016.52.00 10.17.2017"
```

```
Invalid Usage: Error in the JQL Query: Expecting either 'OR' or 'AND' but got '10.17.2017'. (line 1, character 77)
```
