### ISSUE TITLE
Question: Assign issue to Sprint

### ISSUE THREAD

**Issue by BrendanThompson** [Netflix-Skunkworks/go-jira#135]
Hi All,

Just wondering what is the best way to go about assigning an issue to a sprint? Currently I'm not able to do this.

Thanks,

Brendan

**Comment by coryb** [comment]
I have not added this functionality to `go-jira` because the REST apis are pretty fussy to do this seemingly trivial operation.  The basic steps are:
1) identify sprint board id
2) identify active sprint id for given board id
3) assign issues to sprint id

You can do these operations on the command line using the `jira request` command, something like this:
```
board_id=$(jira req "/rest/agile/1.0/board?projectKeyOrId=$JIRA_PROJECT" --gjq values.0.id)
sprint_id=$(jira req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0.id)

**Comment by coryb** [comment]
It is a bit fussy because the `--gjq` filters may not be correct for you if your project has multiple boards, or multiple active sprints.  This filters above assume you have one board and one active sprint, or at least the filters only return the first board/sprint found.

You can attempt to wrap the above commands in a [custom-command](https://github.com/Netflix-Skunkworks/go-jira#custom-commands-1) that would look something like this in your `.jira.d/config.yml`:
```
custom-commands:
  - name: sprint-add
    help: add issue to active sprint for project
    args:
      - name: ISSUE
        required: true
    script: |
      board_id=$({{jira}} req "/rest/agile/1.0/board?projectKeyOrId=$JIRA_PROJECT" --gjq values.0.id)
      sprint_id=$({{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0.id)
      {{jira}} req -M POST "/rest/agile/1.0/sprint/$sprint_id/issue" "{\"issues\":[\"{{args.ISSUE}}\"]}"
```

Then you can run `jira sprint-add ISSUE-123` assuming you have `project: someproject` configured  in your `.jira.d/config.yml`.
