### ISSUE TITLE
Give script templates access to their own name and other metadata

### ISSUE THREAD

**Issue by anthonyrisinger** [Netflix-Skunkworks/go-jira#137]
This is a duplicate of https://github.com/coryb/kingpeon/issues/2, but it's replicated here in the event it can be solved faster/better within `go-jira`.

You can access `options` and `args` via function ([kingpeon.go#L68](https://github.com/coryb/kingpeon/blob/master/kingpeon.go#L68)) but there is no way for a script template to discover the command that triggered it, or other useful information.

I'm trying to make a common entry point like so:

```yaml
custom-commands:
  - name: sync
    options: ...
    args: ...
    script: |
      JIRA={{jira}} exec {{jira}}-lib sync 10<<'EOF'
      {{toJson options}}
      {{toJson args}}
      EOF
```

The script is the same for every custom command except for the word `sync` (or whatever command is in play) because I don't see a way to get that info, eg. `{{.name}}`.

Could we assign `.` to the config so things like `.name` or `.help` work? Or something else?

If there was a `toJson` that returned compact JSON, it would help avoid the quoted heredoc nonsense above, which I'm using as a safe way to pass the prettified, unquoted JSON. Lastly, a `shellquote` function would be massively appreciated! Combined with compact JSON, one could then safely:

```sh
/path/to/command {{options | toJson | shellquote}} {{args | toJson | shellquote}}
```
(It might also be useful to expand `options` to `--opt=abc -ddd ...` or whatever, but I don't need that myself, and prefer to work with the JSON blob version of `options` and `args`)

Shell quoting is pretty straightforward; surround text with `'` and replace single-quotes with `'\''`.
