### ISSUE TITLE
Jira create allow to pass summary and description

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#168]
I'd expect `jira create --issuetype=Task --summary="Test" --description="My description"` to create an issue with the Summary `Test` and `My description` as the description, however the `--summary` and `--description` option are not being recognized.

Is there any reason for this or just an oversight?

**Comment by coryb** [comment]
There is a generic `--override` or `-o` to set arbitrary key=value to use in your templates.  So this should work:
```
jira create --issuetype=Task -o summary="Test" -o description="My description"
```

`--issueType` and `--project` are special because they are used to formulate what is exposed in the template, so different issueTypes or projects will create different template documents to edit.

**Comment by vanniktech** [comment]
That's neat. I've ended up writing a custom command for this:

```yml
- name: ctask
  help: creates a task in the given project
  options:
    - name: project
      short: p
      default: $JIRA_PROJECT
    - name: description
      short: d
      default: ""
  args:
    - name: summary
      required: true
  script: |-
    {{jira}} create --issuetype=Task -o summary="{{args.summary}}" -o description="{{options.description}}" --noedit
```

When I used it like this: `jira ctask "Blub" -d="Description"` everything worked. However in the actual description of the title in jira I saw a `=` prefixed before my description. 

Do you happen to know the reason for this?
