### ISSUE TITLE
Execute multiple commands in a custom command

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#170]
I've got the following custom command `cstory`:

```yml
- name: cstory
  help: creates a story in the given project
  options:
    - name: project
      short: p
      default: $JIRA_PROJECT
    - name: description
      short: d
      default: ""
  args:
    - name: summary
      required: true
  script: |-
    {{jira}} create --issuetype=Story -o summary="{{args.summary}}" -o description="{{options.description}}" --noedit
```

How could I go and get the ticket number that was created from this command let's say `AP-300` and then execute another command within the same custom command. Let's say `jira assign AP-300`.

Maybe something along the lines of:

```yml
script: |-
  ticketNumber = {{jira}} create --issuetype=Story -o summary="{{args.summary}}" -o description="{{options.description}}" --noedit
  jira assign {{ticketNumber}}
```
