### ISSUE TITLE
Allow system variables for endpoint, user, login & project in config.yml

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#172]
Ideally I'd like to configure defaults for endpoint, user, login & project like this:

```yml
endpoint: $JIRA_ENDPOINT
user: $JIRA_USER
login: $JIRA_LOGIN
project: $JIRA_PROJECT
```

Currently that's not possible though. My motivation behind this is that I want to upload my configuration file on Github but not expose any 'sensitive' information.

For custom commands this already does work:

```yml
custom-commands:
  - name: qa
    help: assigns the given ticket to qa
    options:
      - name: assignee
        short: a
        default: $JIRA_DEFAULT_QA_ASSIGNEE
    args:
      - name: ticketnumber
        required: true
    script: |-
      {{jira}} assign {{args.ticketnumber}} {{options.assignee}}
```
