### ISSUE TITLE
"jira ls -a me -S done" doesn't list anything (but "jira ls -q ... does)

### ISSUE THREAD

**Issue by artem-nefedov** [Netflix-Skunkworks/go-jira#182]
If I execute `jira ls -a user -S done`, I get nothing.
However, if I run `jira ls -q "assignee = 'user' and status = 'done'"`, I correctly get a list of tasks assigned to "user" with "Done" status.
I expect those commands to be equal, but apparently they're not.

**Comment by coryb** [comment]
if you have a `query: ...` property defined somewhere in your configs, then that property will be used over the `-S` option.  It is less than ideal, and definately confusing.  So if you have no `query` and use `jira ls -a user -S done` then you will get the JQL: 
```
resolution = unresolved AND AND assignee = 'user' AND status = 'done'
```
You can see the JQL query being used if you use `-vvv` on the command to make it very verbose.  The JQL will be printed out for the https request.

**Comment by artem-nefedov** [comment]
I see. The problem is, there's no option to specify or unset value for `resolution`. So, my question is: how can I list "Done" tickets without writing full query via `-q`, and without changing default behavior?

**Comment by coryb** [comment]
I see, I didn't notice that unresolved and status = done were incompatible.   What we currently have now is either a named query or a custom command.  

The named query would work like this in your `.jira.d/config.yml` file:
```
queries:
  done: |
    assignee = 'user' AND status = 'To Do'
```
Then you would use it with `jira ls -N done`

Otherwise you can make your own command alias like this:
```
custom-commands:
  - name: done
    help: List completed issues
    options:
      - name: user
        short: u
script: |
      {{jira}} ls --query "{{if options.user}}assignee = '{{options.user}}' AND {{end}}status = 'done'"
```
Then `jira done` will use `--query "status = 'done'` or `assignee = 'user' AND status = 'done'`  if the `-u` option is specified.



```

**Comment by artem-nefedov** [comment]
Thanks! The custom command solution does it for me.
I had to rename command and option names to avoid duplicates (also, it makes sense to call option `assignee`, like the one regular `ls` accepts).
My version:
```
  - name: lsdone
    help: List completed issues
    options:
      - name: assignee
        short: a
    script: |-
          {{jira}} ls --query "{{if options.assignee}}assignee = '{{options.assignee}}' AND {{end}}status = 'done'"

```
I did not realize it's possible to use conditions based on options. Is this feature documented somewhere?
