### ISSUE TITLE
How to automatically track the work log time?

### ISSUE THREAD

**Issue by gudata** [Netflix-Skunkworks/go-jira#191]
Hello,
Is there a known way in which i do something like that

```bash
jira worklog start ISSUE
```

...work

```
jira worklog end ISSUE 
```
and jira logs the endtime - startime ?

It can be done with additional scripting but wondering how you doi t?

**Comment by colton22** [comment]
So I already had something similar to this setup.. Very caveman style but re-flavor it as you wish.

```
12:28:42 colton22:~ > cat bin/worklog 
#!/bin/bash

if [ "$1" == "" ] && [ "$2" == "" ]; then
    echo -e "usage: worklog ticket action\n  -action <start|stop>";
    exit;
fi

act=$(echo "$2" |tr '[:upper:]' '[:lower:]');
tkt=$1;

if [ "$act" == "reset" ]; then
    rm ~/.worklog/$tkt;
    echo "$tkt reset!";
    exit;
fi
if [ "$act" != "start" ] && [ "$act" != "stop" ]; then
    echo -e "Action must be start or stop!";
    exit;
fi

if [ "$(tail -n 1 ~/.worklog/$tkt 2>/dev/null |awk -F '|' '{print $1}')" == "$act" ]; then
    echo "$tkt already ${act}ed!";
    exit;
fi
echo "$act|$(date +%s)" >> ~/.worklog/$tkt

if [ "$act" == "start" ]; then
    echo "Logged Start Time in ~/.worklog/$tkt";
else
    #use tail -r on bsd
    log=$(tac ~/.worklog/$tkt);
    sec=0;
    lstop=0;
    bifs=$IFS;
    IFS=$'\n';
    for i in $(echo -e "$log");do
        a=$(echo "$i" |awk -F '|' '{print $1}');
        v=$(echo "$i" |awk -F '|' '{print $2}');
        if [ "$a" == "stop" ]; then
            lstop=$v;
        else
            dif=$(( $lstop - $v ));
            sec=$(( $sec + $dif ));
        fi
    done
    echo "You have worked on $tkt for ${sec}s";
fi
12:28:46 colton22:~ > 
```

I know this does not answer your question but might be a workaround for now. Note you will have to ```mkdir ~/.worklog``` to make it work.

**Comment by colton22** [comment]
aha; just noticed I saved IFS to bifs but never set it back :dancer:

**Comment by coryb** [comment]
I think you can create a few simple aliases in `$HOME/.jira.d/config.yml` for startwork and endwork:

```
custom-commands:
  - name: startwork
    help: mark the start of work on an issue
    args:
      - name: ISSUE
        help: issue to mark work being started on
        required: true
    script: |-
      mkdir -p $HOME/.jira.d/work
      touch -p $HOME/.jira.d/work/{{args.ISSUE}}

  - name: endwork
     help: submit worklog for issue
    args:
      - name: ISSUE
        help: issue to mark work being started on
        required: true
    script: |-
      starttime=$(stat -f "%Sm" -t "%Y-%m-%dT%H:%M:%S.000%z" $HOME.jira.d/work/{{args.ISSUE}})
      {{jira}} worklog add {{args.ISSUE}} -S "$starttime"
```

This effectively allows for  `jira startwork ISSUE-123` and `jira endwork ISSUE-123`.    The `startwork` command really just touches a file.  The `endwork` command will then read the last modified time for the previously touched file and call `jira worklog add ...`. 

I don't use worklogs myself, so I am not 100% sure this will work, but it is where I would start.
