### ISSUE TITLE
override builtin commands

### ISSUE THREAD

**Issue by yruss972** [Netflix-Skunkworks/go-jira#193]
Would love to be able to override built in commands with custom commands, especially for some of the convenience commands like 'done', 'close', etc. which are really just common use cases for transition.

We need to provide custom fields on closing issues and can't add the necessary options to the existing commands.

**Comment by coryb** [comment]
I will look into adding this functionality, but I am limited on time.  You might be able to apply your desired changes for `done`, `close` etc by adding a config file in `.jira.d/done.yml` and `.jira.d/close.yml`.  Those config files can contain any of these properties:
```
overrides:
  key1: val1
  key2: val2

resolution: other-resolution

transition: other-transition
```
