### ISSUE TITLE
Command to transition to 'Need input'

### ISSUE THREAD

**Issue by Zebrazilla** [Netflix-Skunkworks/go-jira#200]
Loving the project thus far and quickly integrating as a vital part in my workflow. However I'm missing a quick command to transition tickets into 'Need input' state, just like there are commands for :in-progress, :todo etc. Any chance this is would be considered? Thanks!

**Comment by coryb** [comment]
the todo etc commands are just wrappers for the `jira transition <state> <issue>` command.  You can create your own aliases with the custom-commands config:
```
custom-commands:
  - name: needsinput
    args:
      - name: ISSUE
    script:   |-
      {{jira}} transition "Needs Input" {{args.ISSUE}}
```

More docs on dynamics commands [here](https://github.com/Netflix-Skunkworks/go-jira#dynamic-configuration).
