### ISSUE TITLE
Custom commands do not honor --endpoint

### ISSUE THREAD

**Issue by krisfremen** [Netflix-Skunkworks/go-jira#205]
I have a custom command

```
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --query "resolution = unresolved and assignee=currentuser() ORDER BY created"
```

This works for the primary endpoint specified in ~/.jira.d/config.yml which is e.g. jira.company.com
```
jira mine
TEST-9:      Test
```

If I override the endpoint it still seems to go the primary endpoint in the config file
```
jira -e http://jira.example.com mine
TEST-9:      Test
```

Running it with -v shows that it's still going to the primary endpoint.

DEBUG Request 1: POST /rest/api/2/search HTTP/1.1
Host: jira.company.com
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Content-Type: application/json

**Comment by schnoddelbotz** [comment]
Note that your custom command invokes `jira` again, without passing through your primary invocation's endpoint. It's indeed a bit of a pity that global options are not available to custom commands / scripts -- try/debug by using `echo {{.}}` as script -- but I think this should do as work-around:

```yaml
custom-commands:
  - name: mine
    help: display issues assigned to me
    options:
      - name: myendpoint
        type: string
        default: http://default-jira.example.com
    script: |-
      {{jira}} -e "{{options.endpoint}}" list --query "resolution = unresolved and assignee=currentuser() ORDER BY created"
```
Invoke it like
```bash
# uses default specified above
jira mine
# override endpoint example:
jira mine --myendpoint http://other-jira.example.com
```

Can you confirm this solves the issue for you?
