### ISSUE TITLE
Evaluating a custom-command in a template

### ISSUE THREAD

**Issue by kevinawoo** [Netflix-Skunkworks/go-jira#209]
Is it possible to evaluate a custom command in the template?

I'm trying to use the create template to fill in the value `customfield_100` which should be the latest sprint (outlined here https://github.com/Netflix-Skunkworks/go-jira/issues/135).  

The Contents of `~/.jira.d/templates/create`:
```yml
fields:
  summary: "new ticket in current sprint"
  description: "this should create a ticket in the current sprint"
  customfield_100:  99  # this should be evaluated to be the current sprint_id
```
