### ISSUE TITLE
Running post-command hooks for normal commands

### ISSUE THREAD

**Issue by wrouesnel** [Netflix-Skunkworks/go-jira#212]
I'd like to be able to run pre and post command hooks when executing go-jira commands.

Specifically I want to tie actions like `jira create` if successful to do things like invoke a `slack-cli` command for me and post some element of what I just did somewhere - as an example.

I suppose this would manifest in the configuration file as a configuration option in `config.yml` for each command - something like:
```yaml
hooks:
  create:
    pre-fill: # Run script before opening the template file, pass the file that the user will be editing
    post-fill-success: # Run the script after the user has filled the template but before sending it
    post-fill-failure: # Run the script after the user cancels sending the result.
    post-send-success: # Run the script after the operation is sent successfully
    post-send-failure: # Run the script if the send operation fails
```

Does this scheme seem remotely sensible? Am I overlooking a way to do this already?
