### ISSUE TITLE
true life custom commands samples

### ISSUE THREAD

**Issue by fabien-michel** [Netflix-Skunkworks/go-jira#230]
Hi,
I'm note very comfortable with custom commands and I am seeking for a bunch of user contributed custom-commands to help me write my owns. The doc seems to be complete, but it would be more instructive to have some real and more complex examples.

There is already a place for this ?
Thanks

**Comment by coryb** [comment]
Here are a few more that I use for my personal projects:
* display list of epic issues with usage `jira epics`
```
custom-commands:
  - name: epics
    help: list epics
    script: |-
      {{jira}} list --template epics --query "resolution = unresolved AND issuetype = Epic AND project = $JIRA_PROJECT ORDER BY Rank Desc" --queryfields=customfield_12551,issuetype,priority,assignee,status,created,reporter
```

* here is a more complex one that tries to figure out the the scrum board id and assign a provided issue to it. There is an option `-n` to assign the issue to the "next" sprint (the "future" one) or the currently "active" one.  Usage: `jira sprint-add ISSUE-123` or `jira sprint-add --next ISSUE-123`
```
custom-command:
  - name: sprint-add
    help: add issue to active sprint for project
    options:
      - name: next
        short: 'n'
        type: bool
        help: add issue to next sprint, rather than the active one
    args:
      - name: ISSUE
        required: true
    script: |
      state={{if options.next}}future{{else}}active{{end}}
      board_id=$({{jira}} req "/rest/agile/1.0/board?projectKeyOrId=$JIRA_PROJECT&type=scrum" --gjq values.0.id)
      sprint_id=$({{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=$state" --gjq values.0.id)
      if [ "$sprint_id" = "" ]; then
        echo "ERROR: No $state sprint" >&2
        exit 1
      fi
      {{jira}} req -M POST "/rest/agile/1.0/sprint/$sprint_id/issue" "{\"issues\":[\"{{args.ISSUE}}\"]}"
```
