### ISSUE TITLE
Ability to use JSESSION token from Cookie for self-hosted JIRA installs?

### ISSUE THREAD

**Issue by noahbetzen-wk** [Netflix-Skunkworks/go-jira#231]
I know the old JSESSION token Cookie method isn't supported in JIRA Cloud, but my company still uses self-hosted JIRA and we log in via SAML; we don't have passwords we can use.

Is there a way to auth in `go-jira` via the old Cookie method either by a command or a line in the config file?

**Comment by rhatfield-bushel** [comment]
So first off, It is possible.

I have my setup working, but it's a bit scripty. I just have a `custom-command` that pulls the cookies from chrome and sets the `~/.jira.d/cookies.js` file:
```shell
#!/bin/bash

eval "$(cd ~/code/chrome-cookie && GOPATH=$PWD && go run cookiemonster.go)"
EXPIRE_DATE="$(date -v "+10d" -u +"%Y-%m-%dT%H:%M:%SZ")"

cat <<EOF > ~/.jira.d/cookies.js
[
  {
    "Name": "atlassian.xsrf.token",
    "Value": "${ATLASSIAN_XSRF_TOKEN}",
    "Path": "/",
    "Domain": "jira.company.net",
    "Expires": "${EXPIRE_DATE}",
    "RawExpires": "",
    "MaxAge": 0,
    "Secure": true,
    "HttpOnly": false,
    "SameSite": 0,
    "Raw": "atlassian.xsrf.token=${ATLASSIAN_XSRF_TOKEN}; Path=/; Secure",
    "Unparsed": null
  },
  {
    "Name": "JSESSIONID",
    "Value": "${JSESSIONID}",
    "Path": "/",
    "Domain": "jira.company.net",
    "Expires": "${EXPIRE_DATE}",
    "RawExpires": "",
    "MaxAge": 0,
    "Secure": true,
    "HttpOnly": true,
    "SameSite": 0,
    "Raw": "JSESSIONID=${JSESSIONID}; Path=/; Secure; HttpOnly",
    "Unparsed": null
  }
]
EOF
```

And the cookiemonster.go file is taken from [here](https://github.com/go-jira/jira/issues/81#issuecomment-471233421), and only outputs the env variables for `JSESSIONID` and `ATLASSIAN_XSRF_TOKEN`:
```golang
package main

import (
	//"code.google.com/p/go.crypto/pbkdf2"
	// "github.com/golang/crypto/pbkdf2"
	"golang.org/x/crypto/pbkdf2"

	"crypto/aes"
	"crypto/cipher"
	"crypto/sha1"
	"database/sql"
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/user"
	"strings"

	_ "github.com/mattn/go-sqlite3"
)

// Inpsiration
// http://n8henrie.com/2013/11/use-chromes-cookies-for-easier-downloading-with-python-requests/

// Chromium Mac os_crypt:  http://dacort.me/1ynPMgx
var (
	salt       = "saltysalt"
	iv         = "                "
	length     = 16
	password   = ""
	iterations = 1003
)

// Cookie - Items for a cookie
type Cookie struct {
	Domain         string
	Key            string
	Value          string
	EncryptedValue []byte
}

// DecryptedValue - Get the unencrypted value of a Chrome cookie
func (c *Cookie) DecryptedValue() string {
	if c.Value > "" {
		return c.Value
	}

	if len(c.EncryptedValue) > 0 {
		encryptedValue := c.EncryptedValue[3:]
		return decryptValue(encryptedValue)
	}

	return ""
}

func usage() {
	fmt.Fprintf(os.Stderr, "usage: %s [domain]\n", os.Args[0])
	os.Exit(2)
}

func main() {
	domain := "jira.company.net"
	password = getPassword()

	// TODO: Output in Netscape format
	for _, cookie := range getCookies(domain) {
		if cookie.Key == "JSESSIONID" {
			fmt.Printf("JSESSIONID=%s\n", cookie.DecryptedValue())
		} else if cookie.Key == "atlassian.xsrf.token" {
			fmt.Printf("ATLASSIAN_XSRF_TOKEN=%s\n", cookie.DecryptedValue())
		}
	}
}

func decryptValue(encryptedValue []byte) string {
	key := pbkdf2.Key([]byte(password), []byte(salt), iterations, length, sha1.New)
	block, err := aes.NewCipher(key)
	if err != nil {
		log.Fatal(err)
	}

	decrypted := make([]byte, len(encryptedValue))
	cbc := cipher.NewCBCDecrypter(block, []byte(iv))
	cbc.CryptBlocks(decrypted, encryptedValue)

	plainText, err := aesStripPadding(decrypted)
	if err != nil {
		fmt.Println("Error decrypting:", err)
		return ""
	}
	return string(plainText)
}

// In the padding scheme the last <padding length> bytes
// have a value equal to the padding length, always in (1,16]
func aesStripPadding(data []byte) ([]byte, error) {
	if len(data)%length != 0 {
		return nil, fmt.Errorf("decrypted data block length is not a multiple of %d", length)
	}
	paddingLen := int(data[len(data)-1])
	if paddingLen > 16 {
		return nil, fmt.Errorf("invalid last block padding length: %d", paddingLen)
	}
	return data[:len(data)-paddingLen], nil
}

func getPassword() string {
	parts := strings.Fields("security find-generic-password -wga Chrome")
	cmd := parts[0]
	parts = parts[1:len(parts)]

	out, err := exec.Command(cmd, parts...).Output()
	if err != nil {
		log.Fatal("error finding password ", err)
	}

	return strings.Trim(string(out), "\n")
}

func getCookies(domain string) (cookies []Cookie) {
	usr, _ := user.Current()
	cookiesFile := fmt.Sprintf("%s/Library/Application Support/Google/Chrome/Default/Cookies", usr.HomeDir)

	db, err := sql.Open("sqlite3", cookiesFile)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT name, value, host_key, encrypted_value FROM cookies WHERE host_key like ?", fmt.Sprintf("%%%s%%", domain))
	if err != nil {
		log.Fatal(err)
	}

	defer rows.Close()
	for rows.Next() {
		var name, value, hostKey string
		var encryptedValue []byte
		rows.Scan(&name, &value, &hostKey, &encryptedValue)
		cookies = append(cookies, Cookie{hostKey, name, value, encryptedValue})
	}

	return
}
```

This is all hobbled together, you'll most likely need some golang and shell script experience to get this going.

**Comment by aurelienmazurie-wk** [comment]
A little contribution to facilitate the use of the `JSESSIONID` and `atlassian.xsrf.token` values: I added a custom command to `~/.jira.d/config.yml` that takes these values as arguments, and write then in `~/.jira.d/cookies.js`:
```yaml
  - name: grab_cookie
    args:
      - name: JSESSIONID
        required: true
      - name: ATLASSIAN_XSRF_TOKEN
        required: true
    script: |-
      EXPIRE_DATE="$(date -v "+10d" -u +"%Y-%m-%dT%H:%M:%SZ")"
      cat <<EOF > ${HOME}/.jira.d/cookies.js
      [
        {
          "Name": "JSESSIONID",
          "Value": "{{args.JSESSIONID}}",
          "Path": "/",
          "Domain": "jira.atl.workiva.net",
          "Expires": "${EXPIRE_DATE}",
          "RawExpires": "",
          "MaxAge": 0,
          "Secure": true,
          "HttpOnly": true,
          "SameSite": 0,
          "Raw": "JSESSIONID={{args.JSESSIONID}}; Path=/; Secure; HttpOnly",
          "Unparsed": null
        },
        {
          "Name": "atlassian.xsrf.token",
          "Value": "{{args.ATLASSIAN_XSRF_TOKEN}}",
          "Path": "/",
          "Domain": "jira.atl.workiva.net",
          "Expires": "${EXPIRE_DATE}",
          "RawExpires": "",
          "MaxAge": 0,
          "Secure": true,
          "HttpOnly": false,
          "SameSite": 0,
          "Raw": "atlassian.xsrf.token={{args.ATLASSIAN_XSRF_TOKEN}}; Path=/; Secure",
          "Unparsed": null
        }
      ]
      EOF
```

**Comment by aurelienmazurie-wk** [comment]
A little contribution to facilitate the use of the `JSESSIONID` and `atlassian.xsrf.token` values: I added a custom command to `~/.jira.d/config.yml` that takes these values as arguments, and write then in `~/.jira.d/cookies.js`:
```yaml
  - name: grab_cookie
    args:
      - name: JSESSIONID
        required: true
      - name: ATLASSIAN_XSRF_TOKEN
        required: true
    script: |-
      EXPIRE_DATE="$(date -v "+10d" -u +"%Y-%m-%dT%H:%M:%SZ")"
      cat <<EOF > ${HOME}/.jira.d/cookies.js
      [
        {
          "Name": "JSESSIONID",
          "Value": "{{args.JSESSIONID}}",
          "Path": "/",
          "Domain": "<your domain>",
          "Expires": "${EXPIRE_DATE}",
          "RawExpires": "",
          "MaxAge": 0,
          "Secure": true,
          "HttpOnly": true,
          "SameSite": 0,
          "Raw": "JSESSIONID={{args.JSESSIONID}}; Path=/; Secure; HttpOnly",
          "Unparsed": null
        },
        {
          "Name": "atlassian.xsrf.token",
          "Value": "{{args.ATLASSIAN_XSRF_TOKEN}}",
          "Path": "/",
          "Domain": "<your domain>",
          "Expires": "${EXPIRE_DATE}",
          "RawExpires": "",
          "MaxAge": 0,
          "Secure": true,
          "HttpOnly": false,
          "SameSite": 0,
          "Raw": "atlassian.xsrf.token={{args.ATLASSIAN_XSRF_TOKEN}}; Path=/; Secure",
          "Unparsed": null
        }
      ]
      EOF
```
