### ISSUE TITLE
How to fill in required options when closing a Jira?

### ISSUE THREAD

**Issue by predatorian3** [Netflix-Skunkworks/go-jira#244]
This is more of a support question, but I was trying to close a Jira and this workflow has a custom option that needs to be supplied when the Jira is closed. How would I supply that option to the Jira when its being transitioned to closed? The example output:

```bash
$ jira close MYTEAM-10958
ERROR customfield_13418: Work Resulted in Prod Change? is required.
✘ Sorry, your reply was invalid: "mypasswordhere" is not a valid answer, please try again.
? Jira reported an error, edit again? No
ERROR Edit Loop aborted by request
```

**Comment by coryb** [comment]
There is a `transition` template that you can modify.
So you would do something like:
```
$ jira export-templates -t transition -d .jira.d/templates
$ vi  .jira.d/templates/transition
```
Note you can use `jira transmeta $ISSUE` to see the metadata structure for your issue workflow

By default `jira` will use `.jira.d/templates/transition` then look in $HOME/.jira.d/templates/transition then use the built-in default template.

**Comment by predatorian3** [comment]
I see what you're talking about, 

```json
                "customfield_13418": {
                    "allowedValues": [
                        {
                            "id": "13589",
                            "self": "https://jira3.company.com/rest/api/2/customFieldOption/13589",
                            "value": "Yes"
                        },
                        {
                            "id": "13590",
                            "self": "https://jira3.company.com/rest/api/2/customFieldOption/13590",
                            "value": "No"
                        }
                    ],
                    "name": "Work Resulted in Prod Change?",
                    "operations": [
                        "set"
                    ],
                    "schema": {
                        "custom": "com.atlassian.jira.plugin.system.customfieldtypes:select",
                        "customId": 13418,
                        "type": "option"
                    }
                },
```

So, I used this. It closed my Jira. Thank you for the help, @coryb 

```yaml
fields:
  assignee:
    name: Predatorian3
  components: 
    - name: Chef
  fixVersions: 
  resolution: 
    name: Done
  customfield_13418: # Was there a Production Change?
    id: "13590"
    value: "No"
transition:
  id: 21
  name: Close Issue
```
