### ISSUE TITLE
Transition not updating comments

### ISSUE THREAD

**Issue by astrostl** [Netflix-Skunkworks/go-jira#45]
Howdy,

When I `jira trans "Done" ID`, I get an expected

```
update:
  comment:
    - add:
        body: |~

fields:
transition:
  id: 31
  name: Done
```

While the transition is successful, any comments put into the comment body don't appear anywhere in the JIRA GUI (Activity/All). I know this is a "custom" (default Scrum board) transition to a "Done" status, but aren't the comments a generic property of issues?

Thanks!
