### ISSUE TITLE
Creating sub-tasks doesn't work or is not obvious

### ISSUE THREAD

**Issue by estahn** [Netflix-Skunkworks/go-jira#69]
I tried to create a sub-task without success. Would it be possible to update the documentation for this.

My template:
```yaml
fields:
  project:
    key: FOOBAR
  issuetype:
    name: Sub-Task
  summary: {{ or .overrides.summary "" }}
  parent:
    key: FOOBAR-307
  priority:
    name: Low
  description: |~

  assignee:
    name:
  reporter:
    name: enricostahn
```

Error Message:
```bash
2017-02-13T13:19:23.274+11:00 ERROR [cli.go:421] Field parent is not editable
2017-02-13T13:19:23.274+11:00 ERROR [main.go:534] Field parent is not editable
```
